//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AdminTbl
    {
        public int AdminID { get; set; }
        [Required(ErrorMessage = "Please provide email here", AllowEmptyStrings = false)]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please provide account name here", AllowEmptyStrings = false)]
        public string AdminName { get; set; }
        [Required(ErrorMessage = "Please provide your business name here", AllowEmptyStrings = false)]
        public string BusinessName { get; set; }
        [Required(ErrorMessage = "Please provide your password here", AllowEmptyStrings = false)]
        [DataType(DataType.Password)]
        [StringLength(50, MinimumLength = 6, ErrorMessage = "Password must be up to 6 character long")]
        public string Password { get; set; }
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "Password does not match")]
        public string ComfirmPassword { get; set; }
        public string LoginErro { get; set; }
        public string UploadProfile { get; set; }
    }
}
